name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    permissions:
      contents: read
      actions: none

    steps:
      - name: Pull latest code from main
        run: |
          cd  /var/www/Mugen-Porta/my-app
          git fetch origin main
          git reset --hard origin/main
          git clean -fd

      - name: Install dependencies
        run: |
          cd  /var/www/Mugen-Porta/my-app
          npm install

      - name: Build app
        run: |
          cd /var/www/Mugen-Porta/my-app
          npm run build

      - name: Restart PM2
        run: |
          pm2 restart mugen
